/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ConfigurationsScanAllPolicy;
import java.io.IOException;

/**
 * Configurations
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-06T02:07:22.019Z")
public class Configurations {
  @SerializedName("auth_mode")
  private String authMode = null;

  @SerializedName("count_per_project")
  private String countPerProject = null;

  @SerializedName("email_from")
  private String emailFrom = null;

  @SerializedName("email_host")
  private String emailHost = null;

  @SerializedName("email_port")
  private Integer emailPort = null;

  @SerializedName("email_identity")
  private String emailIdentity = null;

  @SerializedName("email_username")
  private String emailUsername = null;

  @SerializedName("email_ssl")
  private Boolean emailSsl = null;

  @SerializedName("email_insecure")
  private Boolean emailInsecure = null;

  @SerializedName("ldap_url")
  private String ldapUrl = null;

  @SerializedName("ldap_base_dn")
  private String ldapBaseDn = null;

  @SerializedName("ldap_filter")
  private String ldapFilter = null;

  @SerializedName("ldap_scope")
  private Integer ldapScope = null;

  @SerializedName("ldap_uid")
  private String ldapUid = null;

  @SerializedName("ldap_search_dn")
  private String ldapSearchDn = null;

  @SerializedName("ldap_timeout")
  private Integer ldapTimeout = null;

  @SerializedName("ldap_group_attribute_name")
  private String ldapGroupAttributeName = null;

  @SerializedName("ldap_group_base_dn")
  private String ldapGroupBaseDn = null;

  @SerializedName("ldap_group_search_filter")
  private String ldapGroupSearchFilter = null;

  @SerializedName("ldap_group_search_scope")
  private Integer ldapGroupSearchScope = null;

  @SerializedName("ldap_group_admin_dn")
  private String ldapGroupAdminDn = null;

  @SerializedName("oidc_client_id")
  private String oidcClientId = null;

  @SerializedName("oidc_client_secret")
  private String oidcClientSecret = null;

  @SerializedName("oidc_endpoint")
  private String oidcEndpoint = null;

  @SerializedName("oidc_name")
  private String oidcName = null;

  @SerializedName("oidc_scope")
  private String oidcScope = null;

  @SerializedName("oidc_verify_cert")
  private Boolean oidcVerifyCert = null;

  @SerializedName("project_creation_restriction")
  private String projectCreationRestriction = null;

  @SerializedName("quota_per_project_enable")
  private Boolean quotaPerProjectEnable = null;

  @SerializedName("read_only")
  private Boolean readOnly = null;

  @SerializedName("self_registration")
  private Boolean selfRegistration = null;

  @SerializedName("storage_per_project")
  private String storagePerProject = null;

  @SerializedName("token_expiration")
  private Integer tokenExpiration = null;

  @SerializedName("verify_remote_cert")
  private Boolean verifyRemoteCert = null;

  @SerializedName("scan_all_policy")
  private ConfigurationsScanAllPolicy scanAllPolicy = null;

  public Configurations authMode(String authMode) {
    this.authMode = authMode;
    return this;
  }

   /**
   * The auth mode of current system, such as \&quot;db_auth\&quot;, \&quot;ldap_auth\&quot;
   * @return authMode
  **/
  @ApiModelProperty(value = "The auth mode of current system, such as \"db_auth\", \"ldap_auth\"")
  public String getAuthMode() {
    return authMode;
  }

  public void setAuthMode(String authMode) {
    this.authMode = authMode;
  }

  public Configurations countPerProject(String countPerProject) {
    this.countPerProject = countPerProject;
    return this;
  }

   /**
   * The default count quota for the new created projects.
   * @return countPerProject
  **/
  @ApiModelProperty(value = "The default count quota for the new created projects.")
  public String getCountPerProject() {
    return countPerProject;
  }

  public void setCountPerProject(String countPerProject) {
    this.countPerProject = countPerProject;
  }

  public Configurations emailFrom(String emailFrom) {
    this.emailFrom = emailFrom;
    return this;
  }

   /**
   * The sender name for Email notification.
   * @return emailFrom
  **/
  @ApiModelProperty(value = "The sender name for Email notification.")
  public String getEmailFrom() {
    return emailFrom;
  }

  public void setEmailFrom(String emailFrom) {
    this.emailFrom = emailFrom;
  }

  public Configurations emailHost(String emailHost) {
    this.emailHost = emailHost;
    return this;
  }

   /**
   * The hostname of SMTP server that sends Email notification.
   * @return emailHost
  **/
  @ApiModelProperty(value = "The hostname of SMTP server that sends Email notification.")
  public String getEmailHost() {
    return emailHost;
  }

  public void setEmailHost(String emailHost) {
    this.emailHost = emailHost;
  }

  public Configurations emailPort(Integer emailPort) {
    this.emailPort = emailPort;
    return this;
  }

   /**
   * The port of SMTP server.
   * @return emailPort
  **/
  @ApiModelProperty(value = "The port of SMTP server.")
  public Integer getEmailPort() {
    return emailPort;
  }

  public void setEmailPort(Integer emailPort) {
    this.emailPort = emailPort;
  }

  public Configurations emailIdentity(String emailIdentity) {
    this.emailIdentity = emailIdentity;
    return this;
  }

   /**
   * By default it&#39;s empty so the email_username is picked.
   * @return emailIdentity
  **/
  @ApiModelProperty(value = "By default it's empty so the email_username is picked.")
  public String getEmailIdentity() {
    return emailIdentity;
  }

  public void setEmailIdentity(String emailIdentity) {
    this.emailIdentity = emailIdentity;
  }

  public Configurations emailUsername(String emailUsername) {
    this.emailUsername = emailUsername;
    return this;
  }

   /**
   * The username for authenticate against SMTP server.
   * @return emailUsername
  **/
  @ApiModelProperty(value = "The username for authenticate against SMTP server.")
  public String getEmailUsername() {
    return emailUsername;
  }

  public void setEmailUsername(String emailUsername) {
    this.emailUsername = emailUsername;
  }

  public Configurations emailSsl(Boolean emailSsl) {
    this.emailSsl = emailSsl;
    return this;
  }

   /**
   * When it&#39;s set to true the system will access Email server via TLS by default.  If it&#39;s set to false, it still will handle \&quot;STARTTLS\&quot; from server side.
   * @return emailSsl
  **/
  @ApiModelProperty(value = "When it's set to true the system will access Email server via TLS by default.  If it's set to false, it still will handle \"STARTTLS\" from server side.")
  public Boolean isEmailSsl() {
    return emailSsl;
  }

  public void setEmailSsl(Boolean emailSsl) {
    this.emailSsl = emailSsl;
  }

  public Configurations emailInsecure(Boolean emailInsecure) {
    this.emailInsecure = emailInsecure;
    return this;
  }

   /**
   * Whether or not the certificate will be verified when Harbor tries to access the email server.
   * @return emailInsecure
  **/
  @ApiModelProperty(value = "Whether or not the certificate will be verified when Harbor tries to access the email server.")
  public Boolean isEmailInsecure() {
    return emailInsecure;
  }

  public void setEmailInsecure(Boolean emailInsecure) {
    this.emailInsecure = emailInsecure;
  }

  public Configurations ldapUrl(String ldapUrl) {
    this.ldapUrl = ldapUrl;
    return this;
  }

   /**
   * The URL of LDAP server.
   * @return ldapUrl
  **/
  @ApiModelProperty(value = "The URL of LDAP server.")
  public String getLdapUrl() {
    return ldapUrl;
  }

  public void setLdapUrl(String ldapUrl) {
    this.ldapUrl = ldapUrl;
  }

  public Configurations ldapBaseDn(String ldapBaseDn) {
    this.ldapBaseDn = ldapBaseDn;
    return this;
  }

   /**
   * The Base DN for LDAP binding.
   * @return ldapBaseDn
  **/
  @ApiModelProperty(value = "The Base DN for LDAP binding.")
  public String getLdapBaseDn() {
    return ldapBaseDn;
  }

  public void setLdapBaseDn(String ldapBaseDn) {
    this.ldapBaseDn = ldapBaseDn;
  }

  public Configurations ldapFilter(String ldapFilter) {
    this.ldapFilter = ldapFilter;
    return this;
  }

   /**
   * The filter for LDAP binding.
   * @return ldapFilter
  **/
  @ApiModelProperty(value = "The filter for LDAP binding.")
  public String getLdapFilter() {
    return ldapFilter;
  }

  public void setLdapFilter(String ldapFilter) {
    this.ldapFilter = ldapFilter;
  }

  public Configurations ldapScope(Integer ldapScope) {
    this.ldapScope = ldapScope;
    return this;
  }

   /**
   * 0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE
   * @return ldapScope
  **/
  @ApiModelProperty(value = "0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE")
  public Integer getLdapScope() {
    return ldapScope;
  }

  public void setLdapScope(Integer ldapScope) {
    this.ldapScope = ldapScope;
  }

  public Configurations ldapUid(String ldapUid) {
    this.ldapUid = ldapUid;
    return this;
  }

   /**
   * The attribute which is used as identity for the LDAP binding, such as \&quot;CN\&quot; or \&quot;SAMAccountname\&quot;
   * @return ldapUid
  **/
  @ApiModelProperty(value = "The attribute which is used as identity for the LDAP binding, such as \"CN\" or \"SAMAccountname\"")
  public String getLdapUid() {
    return ldapUid;
  }

  public void setLdapUid(String ldapUid) {
    this.ldapUid = ldapUid;
  }

  public Configurations ldapSearchDn(String ldapSearchDn) {
    this.ldapSearchDn = ldapSearchDn;
    return this;
  }

   /**
   * The DN of the user to do the search.
   * @return ldapSearchDn
  **/
  @ApiModelProperty(value = "The DN of the user to do the search.")
  public String getLdapSearchDn() {
    return ldapSearchDn;
  }

  public void setLdapSearchDn(String ldapSearchDn) {
    this.ldapSearchDn = ldapSearchDn;
  }

  public Configurations ldapTimeout(Integer ldapTimeout) {
    this.ldapTimeout = ldapTimeout;
    return this;
  }

   /**
   * timeout in seconds for connection to LDAP server.
   * @return ldapTimeout
  **/
  @ApiModelProperty(value = "timeout in seconds for connection to LDAP server.")
  public Integer getLdapTimeout() {
    return ldapTimeout;
  }

  public void setLdapTimeout(Integer ldapTimeout) {
    this.ldapTimeout = ldapTimeout;
  }

  public Configurations ldapGroupAttributeName(String ldapGroupAttributeName) {
    this.ldapGroupAttributeName = ldapGroupAttributeName;
    return this;
  }

   /**
   * The attribute which is used as identity of the LDAP group, default is cn.
   * @return ldapGroupAttributeName
  **/
  @ApiModelProperty(value = "The attribute which is used as identity of the LDAP group, default is cn.")
  public String getLdapGroupAttributeName() {
    return ldapGroupAttributeName;
  }

  public void setLdapGroupAttributeName(String ldapGroupAttributeName) {
    this.ldapGroupAttributeName = ldapGroupAttributeName;
  }

  public Configurations ldapGroupBaseDn(String ldapGroupBaseDn) {
    this.ldapGroupBaseDn = ldapGroupBaseDn;
    return this;
  }

   /**
   * The base DN to search LDAP group.
   * @return ldapGroupBaseDn
  **/
  @ApiModelProperty(value = "The base DN to search LDAP group.")
  public String getLdapGroupBaseDn() {
    return ldapGroupBaseDn;
  }

  public void setLdapGroupBaseDn(String ldapGroupBaseDn) {
    this.ldapGroupBaseDn = ldapGroupBaseDn;
  }

  public Configurations ldapGroupSearchFilter(String ldapGroupSearchFilter) {
    this.ldapGroupSearchFilter = ldapGroupSearchFilter;
    return this;
  }

   /**
   * The filter to search the ldap group.
   * @return ldapGroupSearchFilter
  **/
  @ApiModelProperty(value = "The filter to search the ldap group.")
  public String getLdapGroupSearchFilter() {
    return ldapGroupSearchFilter;
  }

  public void setLdapGroupSearchFilter(String ldapGroupSearchFilter) {
    this.ldapGroupSearchFilter = ldapGroupSearchFilter;
  }

  public Configurations ldapGroupSearchScope(Integer ldapGroupSearchScope) {
    this.ldapGroupSearchScope = ldapGroupSearchScope;
    return this;
  }

   /**
   * The scope to search ldap. &#39;0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE&#39;
   * @return ldapGroupSearchScope
  **/
  @ApiModelProperty(value = "The scope to search ldap. '0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE'")
  public Integer getLdapGroupSearchScope() {
    return ldapGroupSearchScope;
  }

  public void setLdapGroupSearchScope(Integer ldapGroupSearchScope) {
    this.ldapGroupSearchScope = ldapGroupSearchScope;
  }

  public Configurations ldapGroupAdminDn(String ldapGroupAdminDn) {
    this.ldapGroupAdminDn = ldapGroupAdminDn;
    return this;
  }

   /**
   * Specify the ldap group which have the same privilege with Harbor admin.
   * @return ldapGroupAdminDn
  **/
  @ApiModelProperty(value = "Specify the ldap group which have the same privilege with Harbor admin.")
  public String getLdapGroupAdminDn() {
    return ldapGroupAdminDn;
  }

  public void setLdapGroupAdminDn(String ldapGroupAdminDn) {
    this.ldapGroupAdminDn = ldapGroupAdminDn;
  }

  public Configurations oidcClientId(String oidcClientId) {
    this.oidcClientId = oidcClientId;
    return this;
  }

   /**
   * The client id of the OIDC.
   * @return oidcClientId
  **/
  @ApiModelProperty(value = "The client id of the OIDC.")
  public String getOidcClientId() {
    return oidcClientId;
  }

  public void setOidcClientId(String oidcClientId) {
    this.oidcClientId = oidcClientId;
  }

  public Configurations oidcClientSecret(String oidcClientSecret) {
    this.oidcClientSecret = oidcClientSecret;
    return this;
  }

   /**
   * The client secret of the OIDC.
   * @return oidcClientSecret
  **/
  @ApiModelProperty(value = "The client secret of the OIDC.")
  public String getOidcClientSecret() {
    return oidcClientSecret;
  }

  public void setOidcClientSecret(String oidcClientSecret) {
    this.oidcClientSecret = oidcClientSecret;
  }

  public Configurations oidcEndpoint(String oidcEndpoint) {
    this.oidcEndpoint = oidcEndpoint;
    return this;
  }

   /**
   * The URL of an OIDC-complaint server, must start with &#39;https://&#39;.
   * @return oidcEndpoint
  **/
  @ApiModelProperty(value = "The URL of an OIDC-complaint server, must start with 'https://'.")
  public String getOidcEndpoint() {
    return oidcEndpoint;
  }

  public void setOidcEndpoint(String oidcEndpoint) {
    this.oidcEndpoint = oidcEndpoint;
  }

  public Configurations oidcName(String oidcName) {
    this.oidcName = oidcName;
    return this;
  }

   /**
   * The name of the OIDC provider.
   * @return oidcName
  **/
  @ApiModelProperty(value = "The name of the OIDC provider.")
  public String getOidcName() {
    return oidcName;
  }

  public void setOidcName(String oidcName) {
    this.oidcName = oidcName;
  }

  public Configurations oidcScope(String oidcScope) {
    this.oidcScope = oidcScope;
    return this;
  }

   /**
   * The scope sent to OIDC server during authentication, should be separated by comma. It has to contain “openid”, and “offline_access”. If you are using google, please remove “offline_access” from this field.
   * @return oidcScope
  **/
  @ApiModelProperty(value = "The scope sent to OIDC server during authentication, should be separated by comma. It has to contain “openid”, and “offline_access”. If you are using google, please remove “offline_access” from this field.")
  public String getOidcScope() {
    return oidcScope;
  }

  public void setOidcScope(String oidcScope) {
    this.oidcScope = oidcScope;
  }

  public Configurations oidcVerifyCert(Boolean oidcVerifyCert) {
    this.oidcVerifyCert = oidcVerifyCert;
    return this;
  }

   /**
   * Whether verify your OIDC server certificate, disable it if your OIDC server is hosted via self-hosted certificate.
   * @return oidcVerifyCert
  **/
  @ApiModelProperty(value = "Whether verify your OIDC server certificate, disable it if your OIDC server is hosted via self-hosted certificate.")
  public Boolean isOidcVerifyCert() {
    return oidcVerifyCert;
  }

  public void setOidcVerifyCert(Boolean oidcVerifyCert) {
    this.oidcVerifyCert = oidcVerifyCert;
  }

  public Configurations projectCreationRestriction(String projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
    return this;
  }

   /**
   * This attribute restricts what users have the permission to create project.  It can be \&quot;everyone\&quot; or \&quot;adminonly\&quot;.
   * @return projectCreationRestriction
  **/
  @ApiModelProperty(value = "This attribute restricts what users have the permission to create project.  It can be \"everyone\" or \"adminonly\".")
  public String getProjectCreationRestriction() {
    return projectCreationRestriction;
  }

  public void setProjectCreationRestriction(String projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
  }

  public Configurations quotaPerProjectEnable(Boolean quotaPerProjectEnable) {
    this.quotaPerProjectEnable = quotaPerProjectEnable;
    return this;
  }

   /**
   * This attribute indicates whether quota per project enabled in harbor
   * @return quotaPerProjectEnable
  **/
  @ApiModelProperty(value = "This attribute indicates whether quota per project enabled in harbor")
  public Boolean isQuotaPerProjectEnable() {
    return quotaPerProjectEnable;
  }

  public void setQuotaPerProjectEnable(Boolean quotaPerProjectEnable) {
    this.quotaPerProjectEnable = quotaPerProjectEnable;
  }

  public Configurations readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * &#39;docker push&#39; is prohibited by Harbor if you set it to true.   
   * @return readOnly
  **/
  @ApiModelProperty(value = "'docker push' is prohibited by Harbor if you set it to true.   ")
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public Configurations selfRegistration(Boolean selfRegistration) {
    this.selfRegistration = selfRegistration;
    return this;
  }

   /**
   * Whether the Harbor instance supports self-registration.  If it&#39;s set to false, admin need to add user to the instance.
   * @return selfRegistration
  **/
  @ApiModelProperty(value = "Whether the Harbor instance supports self-registration.  If it's set to false, admin need to add user to the instance.")
  public Boolean isSelfRegistration() {
    return selfRegistration;
  }

  public void setSelfRegistration(Boolean selfRegistration) {
    this.selfRegistration = selfRegistration;
  }

  public Configurations storagePerProject(String storagePerProject) {
    this.storagePerProject = storagePerProject;
    return this;
  }

   /**
   * The default storage quota for the new created projects.
   * @return storagePerProject
  **/
  @ApiModelProperty(value = "The default storage quota for the new created projects.")
  public String getStoragePerProject() {
    return storagePerProject;
  }

  public void setStoragePerProject(String storagePerProject) {
    this.storagePerProject = storagePerProject;
  }

  public Configurations tokenExpiration(Integer tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
    return this;
  }

   /**
   * The expiration time of the token for internal Registry, in minutes.
   * @return tokenExpiration
  **/
  @ApiModelProperty(value = "The expiration time of the token for internal Registry, in minutes.")
  public Integer getTokenExpiration() {
    return tokenExpiration;
  }

  public void setTokenExpiration(Integer tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
  }

  public Configurations verifyRemoteCert(Boolean verifyRemoteCert) {
    this.verifyRemoteCert = verifyRemoteCert;
    return this;
  }

   /**
   * Whether or not the certificate will be verified when Harbor tries to access a remote Harbor instance for replication.
   * @return verifyRemoteCert
  **/
  @ApiModelProperty(value = "Whether or not the certificate will be verified when Harbor tries to access a remote Harbor instance for replication.")
  public Boolean isVerifyRemoteCert() {
    return verifyRemoteCert;
  }

  public void setVerifyRemoteCert(Boolean verifyRemoteCert) {
    this.verifyRemoteCert = verifyRemoteCert;
  }

  public Configurations scanAllPolicy(ConfigurationsScanAllPolicy scanAllPolicy) {
    this.scanAllPolicy = scanAllPolicy;
    return this;
  }

   /**
   * Get scanAllPolicy
   * @return scanAllPolicy
  **/
  @ApiModelProperty(value = "")
  public ConfigurationsScanAllPolicy getScanAllPolicy() {
    return scanAllPolicy;
  }

  public void setScanAllPolicy(ConfigurationsScanAllPolicy scanAllPolicy) {
    this.scanAllPolicy = scanAllPolicy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Configurations configurations = (Configurations) o;
    return Objects.equals(this.authMode, configurations.authMode) &&
        Objects.equals(this.countPerProject, configurations.countPerProject) &&
        Objects.equals(this.emailFrom, configurations.emailFrom) &&
        Objects.equals(this.emailHost, configurations.emailHost) &&
        Objects.equals(this.emailPort, configurations.emailPort) &&
        Objects.equals(this.emailIdentity, configurations.emailIdentity) &&
        Objects.equals(this.emailUsername, configurations.emailUsername) &&
        Objects.equals(this.emailSsl, configurations.emailSsl) &&
        Objects.equals(this.emailInsecure, configurations.emailInsecure) &&
        Objects.equals(this.ldapUrl, configurations.ldapUrl) &&
        Objects.equals(this.ldapBaseDn, configurations.ldapBaseDn) &&
        Objects.equals(this.ldapFilter, configurations.ldapFilter) &&
        Objects.equals(this.ldapScope, configurations.ldapScope) &&
        Objects.equals(this.ldapUid, configurations.ldapUid) &&
        Objects.equals(this.ldapSearchDn, configurations.ldapSearchDn) &&
        Objects.equals(this.ldapTimeout, configurations.ldapTimeout) &&
        Objects.equals(this.ldapGroupAttributeName, configurations.ldapGroupAttributeName) &&
        Objects.equals(this.ldapGroupBaseDn, configurations.ldapGroupBaseDn) &&
        Objects.equals(this.ldapGroupSearchFilter, configurations.ldapGroupSearchFilter) &&
        Objects.equals(this.ldapGroupSearchScope, configurations.ldapGroupSearchScope) &&
        Objects.equals(this.ldapGroupAdminDn, configurations.ldapGroupAdminDn) &&
        Objects.equals(this.oidcClientId, configurations.oidcClientId) &&
        Objects.equals(this.oidcClientSecret, configurations.oidcClientSecret) &&
        Objects.equals(this.oidcEndpoint, configurations.oidcEndpoint) &&
        Objects.equals(this.oidcName, configurations.oidcName) &&
        Objects.equals(this.oidcScope, configurations.oidcScope) &&
        Objects.equals(this.oidcVerifyCert, configurations.oidcVerifyCert) &&
        Objects.equals(this.projectCreationRestriction, configurations.projectCreationRestriction) &&
        Objects.equals(this.quotaPerProjectEnable, configurations.quotaPerProjectEnable) &&
        Objects.equals(this.readOnly, configurations.readOnly) &&
        Objects.equals(this.selfRegistration, configurations.selfRegistration) &&
        Objects.equals(this.storagePerProject, configurations.storagePerProject) &&
        Objects.equals(this.tokenExpiration, configurations.tokenExpiration) &&
        Objects.equals(this.verifyRemoteCert, configurations.verifyRemoteCert) &&
        Objects.equals(this.scanAllPolicy, configurations.scanAllPolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authMode, countPerProject, emailFrom, emailHost, emailPort, emailIdentity, emailUsername, emailSsl, emailInsecure, ldapUrl, ldapBaseDn, ldapFilter, ldapScope, ldapUid, ldapSearchDn, ldapTimeout, ldapGroupAttributeName, ldapGroupBaseDn, ldapGroupSearchFilter, ldapGroupSearchScope, ldapGroupAdminDn, oidcClientId, oidcClientSecret, oidcEndpoint, oidcName, oidcScope, oidcVerifyCert, projectCreationRestriction, quotaPerProjectEnable, readOnly, selfRegistration, storagePerProject, tokenExpiration, verifyRemoteCert, scanAllPolicy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Configurations {\n");
    
    sb.append("    authMode: ").append(toIndentedString(authMode)).append("\n");
    sb.append("    countPerProject: ").append(toIndentedString(countPerProject)).append("\n");
    sb.append("    emailFrom: ").append(toIndentedString(emailFrom)).append("\n");
    sb.append("    emailHost: ").append(toIndentedString(emailHost)).append("\n");
    sb.append("    emailPort: ").append(toIndentedString(emailPort)).append("\n");
    sb.append("    emailIdentity: ").append(toIndentedString(emailIdentity)).append("\n");
    sb.append("    emailUsername: ").append(toIndentedString(emailUsername)).append("\n");
    sb.append("    emailSsl: ").append(toIndentedString(emailSsl)).append("\n");
    sb.append("    emailInsecure: ").append(toIndentedString(emailInsecure)).append("\n");
    sb.append("    ldapUrl: ").append(toIndentedString(ldapUrl)).append("\n");
    sb.append("    ldapBaseDn: ").append(toIndentedString(ldapBaseDn)).append("\n");
    sb.append("    ldapFilter: ").append(toIndentedString(ldapFilter)).append("\n");
    sb.append("    ldapScope: ").append(toIndentedString(ldapScope)).append("\n");
    sb.append("    ldapUid: ").append(toIndentedString(ldapUid)).append("\n");
    sb.append("    ldapSearchDn: ").append(toIndentedString(ldapSearchDn)).append("\n");
    sb.append("    ldapTimeout: ").append(toIndentedString(ldapTimeout)).append("\n");
    sb.append("    ldapGroupAttributeName: ").append(toIndentedString(ldapGroupAttributeName)).append("\n");
    sb.append("    ldapGroupBaseDn: ").append(toIndentedString(ldapGroupBaseDn)).append("\n");
    sb.append("    ldapGroupSearchFilter: ").append(toIndentedString(ldapGroupSearchFilter)).append("\n");
    sb.append("    ldapGroupSearchScope: ").append(toIndentedString(ldapGroupSearchScope)).append("\n");
    sb.append("    ldapGroupAdminDn: ").append(toIndentedString(ldapGroupAdminDn)).append("\n");
    sb.append("    oidcClientId: ").append(toIndentedString(oidcClientId)).append("\n");
    sb.append("    oidcClientSecret: ").append(toIndentedString(oidcClientSecret)).append("\n");
    sb.append("    oidcEndpoint: ").append(toIndentedString(oidcEndpoint)).append("\n");
    sb.append("    oidcName: ").append(toIndentedString(oidcName)).append("\n");
    sb.append("    oidcScope: ").append(toIndentedString(oidcScope)).append("\n");
    sb.append("    oidcVerifyCert: ").append(toIndentedString(oidcVerifyCert)).append("\n");
    sb.append("    projectCreationRestriction: ").append(toIndentedString(projectCreationRestriction)).append("\n");
    sb.append("    quotaPerProjectEnable: ").append(toIndentedString(quotaPerProjectEnable)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    selfRegistration: ").append(toIndentedString(selfRegistration)).append("\n");
    sb.append("    storagePerProject: ").append(toIndentedString(storagePerProject)).append("\n");
    sb.append("    tokenExpiration: ").append(toIndentedString(tokenExpiration)).append("\n");
    sb.append("    verifyRemoteCert: ").append(toIndentedString(verifyRemoteCert)).append("\n");
    sb.append("    scanAllPolicy: ").append(toIndentedString(scanAllPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

