/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AdminJobScheduleObj;
import java.io.IOException;

/**
 * GCResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-06T02:07:22.019Z")
public class GCResult {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("job_name")
  private String jobName = null;

  @SerializedName("job_kind")
  private String jobKind = null;

  @SerializedName("schedule")
  private AdminJobScheduleObj schedule = null;

  @SerializedName("job_status")
  private String jobStatus = null;

  @SerializedName("deleted")
  private Boolean deleted = null;

  @SerializedName("creation_time")
  private String creationTime = null;

  @SerializedName("update_time")
  private String updateTime = null;

  public GCResult id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * the id of gc job.
   * @return id
  **/
  @ApiModelProperty(value = "the id of gc job.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GCResult jobName(String jobName) {
    this.jobName = jobName;
    return this;
  }

   /**
   * the job name of gc job.
   * @return jobName
  **/
  @ApiModelProperty(value = "the job name of gc job.")
  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }

  public GCResult jobKind(String jobKind) {
    this.jobKind = jobKind;
    return this;
  }

   /**
   * the job kind of gc job.
   * @return jobKind
  **/
  @ApiModelProperty(value = "the job kind of gc job.")
  public String getJobKind() {
    return jobKind;
  }

  public void setJobKind(String jobKind) {
    this.jobKind = jobKind;
  }

  public GCResult schedule(AdminJobScheduleObj schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @ApiModelProperty(value = "")
  public AdminJobScheduleObj getSchedule() {
    return schedule;
  }

  public void setSchedule(AdminJobScheduleObj schedule) {
    this.schedule = schedule;
  }

  public GCResult jobStatus(String jobStatus) {
    this.jobStatus = jobStatus;
    return this;
  }

   /**
   * the status of gc job.
   * @return jobStatus
  **/
  @ApiModelProperty(value = "the status of gc job.")
  public String getJobStatus() {
    return jobStatus;
  }

  public void setJobStatus(String jobStatus) {
    this.jobStatus = jobStatus;
  }

  public GCResult deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * if gc job was deleted.
   * @return deleted
  **/
  @ApiModelProperty(value = "if gc job was deleted.")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public GCResult creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * the creation time of gc job.
   * @return creationTime
  **/
  @ApiModelProperty(value = "the creation time of gc job.")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public GCResult updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * the update time of gc job.
   * @return updateTime
  **/
  @ApiModelProperty(value = "the update time of gc job.")
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GCResult gcResult = (GCResult) o;
    return Objects.equals(this.id, gcResult.id) &&
        Objects.equals(this.jobName, gcResult.jobName) &&
        Objects.equals(this.jobKind, gcResult.jobKind) &&
        Objects.equals(this.schedule, gcResult.schedule) &&
        Objects.equals(this.jobStatus, gcResult.jobStatus) &&
        Objects.equals(this.deleted, gcResult.deleted) &&
        Objects.equals(this.creationTime, gcResult.creationTime) &&
        Objects.equals(this.updateTime, gcResult.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, jobName, jobKind, schedule, jobStatus, deleted, creationTime, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GCResult {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    jobKind: ").append(toIndentedString(jobKind)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    jobStatus: ").append(toIndentedString(jobStatus)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

