/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.GeneralInfoClairVulnerabilityStatus;
import java.io.IOException;

/**
 * GeneralInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-06T02:07:22.019Z")
public class GeneralInfo {
  @SerializedName("with_notary")
  private Boolean withNotary = null;

  @SerializedName("with_clair")
  private Boolean withClair = null;

  @SerializedName("with_admiral")
  private Boolean withAdmiral = null;

  @SerializedName("admiral_endpoint")
  private String admiralEndpoint = null;

  @SerializedName("registry_url")
  private String registryUrl = null;

  @SerializedName("external_url")
  private String externalUrl = null;

  @SerializedName("auth_mode")
  private String authMode = null;

  @SerializedName("project_creation_restriction")
  private String projectCreationRestriction = null;

  @SerializedName("self_registration")
  private Boolean selfRegistration = null;

  @SerializedName("has_ca_root")
  private Boolean hasCaRoot = null;

  @SerializedName("harbor_version")
  private String harborVersion = null;

  @SerializedName("next_scan_all")
  private Integer nextScanAll = null;

  @SerializedName("clair_vulnerability_status")
  private GeneralInfoClairVulnerabilityStatus clairVulnerabilityStatus = null;

  public GeneralInfo withNotary(Boolean withNotary) {
    this.withNotary = withNotary;
    return this;
  }

   /**
   * If the Harbor instance is deployed with nested notary.
   * @return withNotary
  **/
  @ApiModelProperty(value = "If the Harbor instance is deployed with nested notary.")
  public Boolean isWithNotary() {
    return withNotary;
  }

  public void setWithNotary(Boolean withNotary) {
    this.withNotary = withNotary;
  }

  public GeneralInfo withClair(Boolean withClair) {
    this.withClair = withClair;
    return this;
  }

   /**
   * If the Harbor instance is deployed with nested clair.
   * @return withClair
  **/
  @ApiModelProperty(value = "If the Harbor instance is deployed with nested clair.")
  public Boolean isWithClair() {
    return withClair;
  }

  public void setWithClair(Boolean withClair) {
    this.withClair = withClair;
  }

  public GeneralInfo withAdmiral(Boolean withAdmiral) {
    this.withAdmiral = withAdmiral;
    return this;
  }

   /**
   * If the Harbor instance is deployed with Admiral.
   * @return withAdmiral
  **/
  @ApiModelProperty(value = "If the Harbor instance is deployed with Admiral.")
  public Boolean isWithAdmiral() {
    return withAdmiral;
  }

  public void setWithAdmiral(Boolean withAdmiral) {
    this.withAdmiral = withAdmiral;
  }

  public GeneralInfo admiralEndpoint(String admiralEndpoint) {
    this.admiralEndpoint = admiralEndpoint;
    return this;
  }

   /**
   * The url of the endpoint of admiral instance.
   * @return admiralEndpoint
  **/
  @ApiModelProperty(value = "The url of the endpoint of admiral instance.")
  public String getAdmiralEndpoint() {
    return admiralEndpoint;
  }

  public void setAdmiralEndpoint(String admiralEndpoint) {
    this.admiralEndpoint = admiralEndpoint;
  }

  public GeneralInfo registryUrl(String registryUrl) {
    this.registryUrl = registryUrl;
    return this;
  }

   /**
   * The url of registry against which the docker command should be issued.
   * @return registryUrl
  **/
  @ApiModelProperty(value = "The url of registry against which the docker command should be issued.")
  public String getRegistryUrl() {
    return registryUrl;
  }

  public void setRegistryUrl(String registryUrl) {
    this.registryUrl = registryUrl;
  }

  public GeneralInfo externalUrl(String externalUrl) {
    this.externalUrl = externalUrl;
    return this;
  }

   /**
   * The external URL of Harbor, with protocol.
   * @return externalUrl
  **/
  @ApiModelProperty(value = "The external URL of Harbor, with protocol.")
  public String getExternalUrl() {
    return externalUrl;
  }

  public void setExternalUrl(String externalUrl) {
    this.externalUrl = externalUrl;
  }

  public GeneralInfo authMode(String authMode) {
    this.authMode = authMode;
    return this;
  }

   /**
   * The auth mode of current Harbor instance.
   * @return authMode
  **/
  @ApiModelProperty(value = "The auth mode of current Harbor instance.")
  public String getAuthMode() {
    return authMode;
  }

  public void setAuthMode(String authMode) {
    this.authMode = authMode;
  }

  public GeneralInfo projectCreationRestriction(String projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
    return this;
  }

   /**
   * Indicate who can create projects, it could be &#39;adminonly&#39; or &#39;everyone&#39;.
   * @return projectCreationRestriction
  **/
  @ApiModelProperty(value = "Indicate who can create projects, it could be 'adminonly' or 'everyone'.")
  public String getProjectCreationRestriction() {
    return projectCreationRestriction;
  }

  public void setProjectCreationRestriction(String projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
  }

  public GeneralInfo selfRegistration(Boolean selfRegistration) {
    this.selfRegistration = selfRegistration;
    return this;
  }

   /**
   * Indicate whether the Harbor instance enable user to register himself.
   * @return selfRegistration
  **/
  @ApiModelProperty(value = "Indicate whether the Harbor instance enable user to register himself.")
  public Boolean isSelfRegistration() {
    return selfRegistration;
  }

  public void setSelfRegistration(Boolean selfRegistration) {
    this.selfRegistration = selfRegistration;
  }

  public GeneralInfo hasCaRoot(Boolean hasCaRoot) {
    this.hasCaRoot = hasCaRoot;
    return this;
  }

   /**
   * Indicate whether there is a ca root cert file ready for download in the file system.
   * @return hasCaRoot
  **/
  @ApiModelProperty(value = "Indicate whether there is a ca root cert file ready for download in the file system.")
  public Boolean isHasCaRoot() {
    return hasCaRoot;
  }

  public void setHasCaRoot(Boolean hasCaRoot) {
    this.hasCaRoot = hasCaRoot;
  }

  public GeneralInfo harborVersion(String harborVersion) {
    this.harborVersion = harborVersion;
    return this;
  }

   /**
   * The build version of Harbor.
   * @return harborVersion
  **/
  @ApiModelProperty(value = "The build version of Harbor.")
  public String getHarborVersion() {
    return harborVersion;
  }

  public void setHarborVersion(String harborVersion) {
    this.harborVersion = harborVersion;
  }

  public GeneralInfo nextScanAll(Integer nextScanAll) {
    this.nextScanAll = nextScanAll;
    return this;
  }

   /**
   * The UTC time in milliseconds, after which user can call scanAll API to scan all images.
   * @return nextScanAll
  **/
  @ApiModelProperty(value = "The UTC time in milliseconds, after which user can call scanAll API to scan all images.")
  public Integer getNextScanAll() {
    return nextScanAll;
  }

  public void setNextScanAll(Integer nextScanAll) {
    this.nextScanAll = nextScanAll;
  }

  public GeneralInfo clairVulnerabilityStatus(GeneralInfoClairVulnerabilityStatus clairVulnerabilityStatus) {
    this.clairVulnerabilityStatus = clairVulnerabilityStatus;
    return this;
  }

   /**
   * Get clairVulnerabilityStatus
   * @return clairVulnerabilityStatus
  **/
  @ApiModelProperty(value = "")
  public GeneralInfoClairVulnerabilityStatus getClairVulnerabilityStatus() {
    return clairVulnerabilityStatus;
  }

  public void setClairVulnerabilityStatus(GeneralInfoClairVulnerabilityStatus clairVulnerabilityStatus) {
    this.clairVulnerabilityStatus = clairVulnerabilityStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneralInfo generalInfo = (GeneralInfo) o;
    return Objects.equals(this.withNotary, generalInfo.withNotary) &&
        Objects.equals(this.withClair, generalInfo.withClair) &&
        Objects.equals(this.withAdmiral, generalInfo.withAdmiral) &&
        Objects.equals(this.admiralEndpoint, generalInfo.admiralEndpoint) &&
        Objects.equals(this.registryUrl, generalInfo.registryUrl) &&
        Objects.equals(this.externalUrl, generalInfo.externalUrl) &&
        Objects.equals(this.authMode, generalInfo.authMode) &&
        Objects.equals(this.projectCreationRestriction, generalInfo.projectCreationRestriction) &&
        Objects.equals(this.selfRegistration, generalInfo.selfRegistration) &&
        Objects.equals(this.hasCaRoot, generalInfo.hasCaRoot) &&
        Objects.equals(this.harborVersion, generalInfo.harborVersion) &&
        Objects.equals(this.nextScanAll, generalInfo.nextScanAll) &&
        Objects.equals(this.clairVulnerabilityStatus, generalInfo.clairVulnerabilityStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(withNotary, withClair, withAdmiral, admiralEndpoint, registryUrl, externalUrl, authMode, projectCreationRestriction, selfRegistration, hasCaRoot, harborVersion, nextScanAll, clairVulnerabilityStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneralInfo {\n");
    
    sb.append("    withNotary: ").append(toIndentedString(withNotary)).append("\n");
    sb.append("    withClair: ").append(toIndentedString(withClair)).append("\n");
    sb.append("    withAdmiral: ").append(toIndentedString(withAdmiral)).append("\n");
    sb.append("    admiralEndpoint: ").append(toIndentedString(admiralEndpoint)).append("\n");
    sb.append("    registryUrl: ").append(toIndentedString(registryUrl)).append("\n");
    sb.append("    externalUrl: ").append(toIndentedString(externalUrl)).append("\n");
    sb.append("    authMode: ").append(toIndentedString(authMode)).append("\n");
    sb.append("    projectCreationRestriction: ").append(toIndentedString(projectCreationRestriction)).append("\n");
    sb.append("    selfRegistration: ").append(toIndentedString(selfRegistration)).append("\n");
    sb.append("    hasCaRoot: ").append(toIndentedString(hasCaRoot)).append("\n");
    sb.append("    harborVersion: ").append(toIndentedString(harborVersion)).append("\n");
    sb.append("    nextScanAll: ").append(toIndentedString(nextScanAll)).append("\n");
    sb.append("    clairVulnerabilityStatus: ").append(toIndentedString(clairVulnerabilityStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

