/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The object of robot account
 */
@ApiModel(description = "The object of robot account")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-06T02:07:22.019Z")
public class RobotAccount {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("expires_at")
  private Integer expiresAt = null;

  @SerializedName("project_id")
  private Integer projectId = null;

  @SerializedName("disabled")
  private Boolean disabled = null;

  @SerializedName("creation_time")
  private String creationTime = null;

  @SerializedName("update_time")
  private String updateTime = null;

  public RobotAccount id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The id of robot account
   * @return id
  **/
  @ApiModelProperty(value = "The id of robot account")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RobotAccount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of robot account
   * @return name
  **/
  @ApiModelProperty(value = "The name of robot account")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RobotAccount description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of robot account
   * @return description
  **/
  @ApiModelProperty(value = "The description of robot account")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RobotAccount expiresAt(Integer expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * The expiration of robot account (in seconds)
   * @return expiresAt
  **/
  @ApiModelProperty(value = "The expiration of robot account (in seconds)")
  public Integer getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(Integer expiresAt) {
    this.expiresAt = expiresAt;
  }

  public RobotAccount projectId(Integer projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * The project id of robot account
   * @return projectId
  **/
  @ApiModelProperty(value = "The project id of robot account")
  public Integer getProjectId() {
    return projectId;
  }

  public void setProjectId(Integer projectId) {
    this.projectId = projectId;
  }

  public RobotAccount disabled(Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

   /**
   * The robot account is disable or enable
   * @return disabled
  **/
  @ApiModelProperty(value = "The robot account is disable or enable")
  public Boolean isDisabled() {
    return disabled;
  }

  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }

  public RobotAccount creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * The creation time of the robot account
   * @return creationTime
  **/
  @ApiModelProperty(value = "The creation time of the robot account")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public RobotAccount updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * The update time of the robot account
   * @return updateTime
  **/
  @ApiModelProperty(value = "The update time of the robot account")
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RobotAccount robotAccount = (RobotAccount) o;
    return Objects.equals(this.id, robotAccount.id) &&
        Objects.equals(this.name, robotAccount.name) &&
        Objects.equals(this.description, robotAccount.description) &&
        Objects.equals(this.expiresAt, robotAccount.expiresAt) &&
        Objects.equals(this.projectId, robotAccount.projectId) &&
        Objects.equals(this.disabled, robotAccount.disabled) &&
        Objects.equals(this.creationTime, robotAccount.creationTime) &&
        Objects.equals(this.updateTime, robotAccount.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, expiresAt, projectId, disabled, creationTime, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RobotAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

