/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ScannerCapability
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-06T02:07:22.019Z")
public class ScannerCapability {
  @SerializedName("consumes_mime_types")
  private List<String> consumesMimeTypes = null;

  @SerializedName("produces_mime_types")
  private List<String> producesMimeTypes = null;

  public ScannerCapability consumesMimeTypes(List<String> consumesMimeTypes) {
    this.consumesMimeTypes = consumesMimeTypes;
    return this;
  }

  public ScannerCapability addConsumesMimeTypesItem(String consumesMimeTypesItem) {
    if (this.consumesMimeTypes == null) {
      this.consumesMimeTypes = new ArrayList<String>();
    }
    this.consumesMimeTypes.add(consumesMimeTypesItem);
    return this;
  }

   /**
   * Get consumesMimeTypes
   * @return consumesMimeTypes
  **/
  @ApiModelProperty(value = "")
  public List<String> getConsumesMimeTypes() {
    return consumesMimeTypes;
  }

  public void setConsumesMimeTypes(List<String> consumesMimeTypes) {
    this.consumesMimeTypes = consumesMimeTypes;
  }

  public ScannerCapability producesMimeTypes(List<String> producesMimeTypes) {
    this.producesMimeTypes = producesMimeTypes;
    return this;
  }

  public ScannerCapability addProducesMimeTypesItem(String producesMimeTypesItem) {
    if (this.producesMimeTypes == null) {
      this.producesMimeTypes = new ArrayList<String>();
    }
    this.producesMimeTypes.add(producesMimeTypesItem);
    return this;
  }

   /**
   * Get producesMimeTypes
   * @return producesMimeTypes
  **/
  @ApiModelProperty(value = "")
  public List<String> getProducesMimeTypes() {
    return producesMimeTypes;
  }

  public void setProducesMimeTypes(List<String> producesMimeTypes) {
    this.producesMimeTypes = producesMimeTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScannerCapability scannerCapability = (ScannerCapability) o;
    return Objects.equals(this.consumesMimeTypes, scannerCapability.consumesMimeTypes) &&
        Objects.equals(this.producesMimeTypes, scannerCapability.producesMimeTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumesMimeTypes, producesMimeTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScannerCapability {\n");
    
    sb.append("    consumesMimeTypes: ").append(toIndentedString(consumesMimeTypes)).append("\n");
    sb.append("    producesMimeTypes: ").append(toIndentedString(producesMimeTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

