/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Scanner;
import io.swagger.client.model.ScannerCapability;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The metadata info of the scanner adapter
 */
@ApiModel(description = "The metadata info of the scanner adapter")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-06T02:07:22.019Z")
public class ScannerAdapterMetadata {
  @SerializedName("name")
  private Scanner name = null;

  @SerializedName("capabilities")
  private List<ScannerCapability> capabilities = null;

  @SerializedName("properties")
  private Map<String, String> properties = null;

  public ScannerAdapterMetadata name(Scanner name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public Scanner getName() {
    return name;
  }

  public void setName(Scanner name) {
    this.name = name;
  }

  public ScannerAdapterMetadata capabilities(List<ScannerCapability> capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  public ScannerAdapterMetadata addCapabilitiesItem(ScannerCapability capabilitiesItem) {
    if (this.capabilities == null) {
      this.capabilities = new ArrayList<ScannerCapability>();
    }
    this.capabilities.add(capabilitiesItem);
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @ApiModelProperty(value = "")
  public List<ScannerCapability> getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(List<ScannerCapability> capabilities) {
    this.capabilities = capabilities;
  }

  public ScannerAdapterMetadata properties(Map<String, String> properties) {
    this.properties = properties;
    return this;
  }

  public ScannerAdapterMetadata putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<String, String>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(example = "{\"harbor.scanner-adapter/registry-authorization-type\":\"Bearer\"}", value = "")
  public Map<String, String> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, String> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScannerAdapterMetadata scannerAdapterMetadata = (ScannerAdapterMetadata) o;
    return Objects.equals(this.name, scannerAdapterMetadata.name) &&
        Objects.equals(this.capabilities, scannerAdapterMetadata.capabilities) &&
        Objects.equals(this.properties, scannerAdapterMetadata.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, capabilities, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScannerAdapterMetadata {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

