/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Label;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LabelApi
 */
@Ignore
public class LabelApiTest {

    private final LabelApi api = new LabelApi();

    
    /**
     * Return the attahced labels of chart.
     *
     * Return the attahced labels of the specified chart version.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void chartrepoRepoChartsNameVersionLabelsGetTest() throws ApiException {
        String repo = null;
        String name = null;
        String version = null;
        api.chartrepoRepoChartsNameVersionLabelsGet(repo, name, version);

        // TODO: test validations
    }
    
    /**
     * Remove label from chart.
     *
     * Remove label from the specified chart version.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void chartrepoRepoChartsNameVersionLabelsIdDeleteTest() throws ApiException {
        String repo = null;
        String name = null;
        String version = null;
        Integer id = null;
        api.chartrepoRepoChartsNameVersionLabelsIdDelete(repo, name, version, id);

        // TODO: test validations
    }
    
    /**
     * Mark label to chart.
     *
     * Mark label to the specified chart version.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void chartrepoRepoChartsNameVersionLabelsPostTest() throws ApiException {
        String repo = null;
        String name = null;
        String version = null;
        Label label = null;
        api.chartrepoRepoChartsNameVersionLabelsPost(repo, name, version, label);

        // TODO: test validations
    }
    
}
