/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Quota;
import io.swagger.client.model.QuotaUpdateReq;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QuotaApi
 */
@Ignore
public class QuotaApiTest {

    private final QuotaApi api = new QuotaApi();

    
    /**
     * Get the specified quota
     *
     * Get the specified quota
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void quotasIdGetTest() throws ApiException {
        Integer id = null;
        Quota response = api.quotasIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Update the specified quota
     *
     * Update hard limits of the specified quota
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void quotasIdPutTest() throws ApiException {
        Integer id = null;
        QuotaUpdateReq hard = null;
        api.quotasIdPut(id, hard);

        // TODO: test validations
    }
    
}
