/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Report;
import io.swagger.client.model.Stats;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScanApi
 */
@Ignore
public class ScanApiTest {

    private final ScanApi api = new ScanApi();

    
    /**
     * Get the scan report
     *
     * Retrieve the scan report for the artifact identified by the repo_name and tag. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void repositoriesRepoNameTagsTagScanGetTest() throws ApiException {
        String repoName = null;
        String tag = null;
        String accept = null;
        Report response = api.repositoriesRepoNameTagsTagScanGet(repoName, tag, accept);

        // TODO: test validations
    }
    
    /**
     * Scan the image.
     *
     * Trigger a scan targeting the artifact identified by the repo_name and tag. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void repositoriesRepoNameTagsTagScanPostTest() throws ApiException {
        String repoName = null;
        String tag = null;
        api.repositoriesRepoNameTagsTagScanPost(repoName, tag);

        // TODO: test validations
    }
    
    /**
     * Get scan log
     *
     * Get the log text stream for the given artifact and scan action.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void repositoriesRepoNameTagsTagScanUuidLogGetTest() throws ApiException {
        String repoName = null;
        String tag = null;
        String uuid = null;
        String response = api.repositoriesRepoNameTagsTagScanUuidLogGet(repoName, tag, uuid);

        // TODO: test validations
    }
    
    /**
     * Get the metrics of the latest scan all process
     *
     * Get the metrics of the latest scan all process
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scansAllMetricsGetTest() throws ApiException {
        Stats response = api.scansAllMetricsGet();

        // TODO: test validations
    }
    
    /**
     * Get the metrics of the latest scheduled scan all process
     *
     * Get the metrics of the latest scheduled scan all process
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scansScheduleMetricsGetTest() throws ApiException {
        Stats response = api.scansScheduleMetricsGet();

        // TODO: test validations
    }
    
}
